require 'cocoapods-freezer/freezer'
require 'cocoapods-freezer/dir'
require 'cocoapods-freezer/config'
require 'cocoapods-freezer/installer'
require 'cocoapods-freezer/xcodebuild'
require 'cocoapods-freezer/lipo'
require 'cocoapods-freezer/specification'
require 'cocoapods-freezer/sandbox'
require 'cocoapods-freezer/lockfile'
require 'cocoapods-freezer/command'

